# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kxs399-kv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: 'Tar files'
      run: | 
        mkdir artifacts
        tar -cvf node-app.tar .
        ls -ltr
        mv node-app.tar artifacts
        ls -ltr
        
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: artifacts/node-app.tar    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:          

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app
        path: artifacts/node-app.tar 
       
    - name: 'UnTar files'
      run: |
        mkdir node-app
        ls -ltra
        cd artifacts
        ls -ltra
        mv node-app.tar ../node-app
        cd node-app
        ls -ltra
        tar -xvf node-app.tar
        
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kxs399-kv'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_728e43b6bfb54d1b8dd769d72fa28d55 }}
        package: node-app
